name: Docs

on:
  push:
    branches: [ main ]
  # TODO: remove this!
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          pip3 install -r requirements.txt
          pip3 install pdoc3
      - name: Generate
        run: pdoc3 --html loda
      - name: Deploy
        run: |
          git clone -b gh-pages "https://loda-bot:${{ secrets.LODA_BOT_TOKEN }}@github.com/loda-lang/loda-python.git" $HOME/gh-pages
          git -C $HOME/gh-pages config user.name "LODA Bot"
          git -C $HOME/gh-pages config user.email "loda@ckrause.org"
          rm -r $HOME/gh-pages/docs
          mv html/loda $HOME/gh-pages/docs
          rmdir html
          git -C $HOME/gh-pages add docs
          git -C $HOME/gh-pages commit -m "update docs"
          git -C $HOME/gh-pages push
          rm -rf $HOME/gh-pages
