name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        run: pip install -r requirements.txt
      - name: Test
        run: nose2 tests -v
      - name: Sample
        run: python3 sample.py
