name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          pip3 install -r requirements.txt
          pip3 install pdoc3
      - name: Test
        run: nose2 tests -v
      - name: Docs
        run: pdoc3 --html loda
